create extension if not exists pgcrypto;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text,
  full_name text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_username_length check (username is null or char_length(trim(username)) between 3 and 24)
);

create unique index profiles_username_lower_unique
  on public.profiles (lower(username))
  where username is not null;

create table public.venues (
  id text primary key,
  creator_id uuid references auth.users(id) on delete set null,
  name text not null,
  latitude double precision not null check (latitude between -90 and 90),
  longitude double precision not null check (longitude between -180 and 180),
  address text,
  category text not null check (category in ('BAR','PUB','NIGHTCLUB','BIERGARTEN','OTHER')),
  source text not null check (source in ('OSM','MANUAL')),
  external_id text,
  created_at timestamptz not null default now()
);

create index venues_location_idx on public.venues (latitude, longitude);
create index venues_external_id_idx on public.venues (external_id) where external_id is not null;

create table public.outings (
  id text primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  title text,
  description text,
  started_at timestamptz not null,
  ended_at timestamptz,
  status text not null check (status in ('ACTIVE','FINISHED','CANCELLED')),
  city text,
  current_venue_id text references public.venues(id) on delete set null,
  distance_meters double precision not null default 0 check (distance_meters >= 0),
  visibility text not null default 'PRIVATE' check (visibility in ('PUBLIC','FOLLOWERS','PRIVATE')),
  drink_visibility text not null default 'PRIVATE' check (drink_visibility in ('PUBLIC','PARTICIPANTS','PRIVATE')),
  map_visibility text not null default 'PRIVATE' check (map_visibility in ('FULL','HIDE_START_END','PRIVATE')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint outings_dates_check check (ended_at is null or ended_at >= started_at)
);

create index outings_owner_started_idx on public.outings (owner_id, started_at desc);
create index outings_status_idx on public.outings (status);

create table public.outing_stops (
  id text primary key,
  outing_id text not null references public.outings(id) on delete cascade,
  venue_id text not null references public.venues(id) on delete restrict,
  arrived_at timestamptz not null,
  departed_at timestamptz,
  order_index integer not null check (order_index >= 0),
  constraint outing_stops_dates_check check (departed_at is null or departed_at >= arrived_at),
  unique (outing_id, order_index)
);

create index outing_stops_outing_idx on public.outing_stops (outing_id, order_index);

create table public.drinks (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  outing_id text not null references public.outings(id) on delete cascade,
  venue_id text references public.venues(id) on delete set null,
  type text not null check (type in ('BEER','KALIMOTXO','SHOT','MIXED_DRINK')),
  beer_size text check (beer_size is null or beer_size in ('QUINTO','TERCIO','LITRONA')),
  subtype text,
  notes text,
  consumed_at timestamptz not null,
  latitude double precision check (latitude is null or latitude between -90 and 90),
  longitude double precision check (longitude is null or longitude between -180 and 180),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint drinks_type_size_consistency check (
    (type = 'BEER' and beer_size is not null)
    or (type <> 'BEER' and beer_size is null)
  )
);

create index drinks_outing_time_idx on public.drinks (outing_id, consumed_at);
create index drinks_user_time_idx on public.drinks (user_id, consumed_at desc);

create table public.route_points (
  id bigint generated by default as identity primary key,
  outing_id text not null references public.outings(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  point_index integer not null check (point_index >= 0),
  latitude double precision not null check (latitude between -90 and 90),
  longitude double precision not null check (longitude between -180 and 180),
  accuracy double precision,
  altitude double precision,
  speed double precision,
  recorded_at timestamptz not null,
  unique (outing_id, point_index)
);

create index route_points_outing_idx on public.route_points (outing_id, point_index);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create trigger outings_set_updated_at
before update on public.outings
for each row execute function public.set_updated_at();

create trigger drinks_set_updated_at
before update on public.drinks
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name'),
    coalesce(new.raw_user_meta_data ->> 'avatar_url', new.raw_user_meta_data ->> 'picture')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.venues enable row level security;
alter table public.outings enable row level security;
alter table public.outing_stops enable row level security;
alter table public.drinks enable row level security;
alter table public.route_points enable row level security;

create policy profiles_select_authenticated
on public.profiles for select
to authenticated
using (true);

create policy profiles_update_own
on public.profiles for update
to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

create policy venues_select_authenticated
on public.venues for select
to authenticated
using (true);

create policy venues_insert_own
on public.venues for insert
to authenticated
with check (creator_id = (select auth.uid()));

create policy venues_update_own
on public.venues for update
to authenticated
using (creator_id = (select auth.uid()))
with check (creator_id = (select auth.uid()));

create policy outings_select_own
on public.outings for select
to authenticated
using (owner_id = (select auth.uid()));

create policy outings_insert_own
on public.outings for insert
to authenticated
with check (owner_id = (select auth.uid()));

create policy outings_update_own
on public.outings for update
to authenticated
using (owner_id = (select auth.uid()))
with check (owner_id = (select auth.uid()));

create policy outings_delete_own
on public.outings for delete
to authenticated
using (owner_id = (select auth.uid()));

create policy outing_stops_select_own
on public.outing_stops for select
to authenticated
using (exists (
  select 1 from public.outings o
  where o.id = outing_stops.outing_id
    and o.owner_id = (select auth.uid())
));

create policy outing_stops_insert_own
on public.outing_stops for insert
to authenticated
with check (exists (
  select 1 from public.outings o
  where o.id = outing_stops.outing_id
    and o.owner_id = (select auth.uid())
));

create policy outing_stops_update_own
on public.outing_stops for update
to authenticated
using (exists (
  select 1 from public.outings o
  where o.id = outing_stops.outing_id
    and o.owner_id = (select auth.uid())
))
with check (exists (
  select 1 from public.outings o
  where o.id = outing_stops.outing_id
    and o.owner_id = (select auth.uid())
));

create policy outing_stops_delete_own
on public.outing_stops for delete
to authenticated
using (exists (
  select 1 from public.outings o
  where o.id = outing_stops.outing_id
    and o.owner_id = (select auth.uid())
));

create policy drinks_select_own
on public.drinks for select
to authenticated
using (user_id = (select auth.uid()));

create policy drinks_insert_own
on public.drinks for insert
to authenticated
with check (
  user_id = (select auth.uid())
  and exists (
    select 1 from public.outings o
    where o.id = drinks.outing_id
      and o.owner_id = (select auth.uid())
  )
);

create policy drinks_update_own
on public.drinks for update
to authenticated
using (user_id = (select auth.uid()))
with check (user_id = (select auth.uid()));

create policy drinks_delete_own
on public.drinks for delete
to authenticated
using (user_id = (select auth.uid()));

create policy route_points_select_own
on public.route_points for select
to authenticated
using (user_id = (select auth.uid()));

create policy route_points_insert_own
on public.route_points for insert
to authenticated
with check (
  user_id = (select auth.uid())
  and exists (
    select 1 from public.outings o
    where o.id = route_points.outing_id
      and o.owner_id = (select auth.uid())
  )
);

create policy route_points_delete_own
on public.route_points for delete
to authenticated
using (user_id = (select auth.uid()));

grant usage on schema public to authenticated;
grant select, update on public.profiles to authenticated;
grant select, insert, update on public.venues to authenticated;
grant select, insert, update, delete on public.outings to authenticated;
grant select, insert, update, delete on public.outing_stops to authenticated;
grant select, insert, update, delete on public.drinks to authenticated;
grant select, insert, delete on public.route_points to authenticated;
grant usage, select on sequence public.route_points_id_seq to authenticated;
